# Generated by Django 4.1 on 2022-08-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='load',
            field=models.FileField(default='default.txt', upload_to='users_files', verbose_name='Файл от пользователя'),
        ),
    ]
